### ISSUE TITLE
Error while install cryptopia module

### ISSUE THREAD

**Issue by peguiny** [thebotguys/cryptopia-api-python#19]
Tried pip install https://github.com/crypto-crew-tech/cryptopia-api-python
```
Collecting https://github.com/crypto-crew-tech/cryptopia-api-python
  Downloading https://github.com/crypto-crew-tech/cryptopia-api-python
     | 71kB 398kB/s
  Cannot unpack file C:\Users\WEIJIE~1\AppData\Local\Temp\pip-yvqnpx25-unpack\cryptopia-api-python (downloaded from C:\Users\WEIJIE~1\AppData\Local\Temp\pip-n_1fbk66-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of C:\Users\WEIJIE~1\AppData\Local\Temp\pip-n_1fbk66-build
```

Tried >pip install git+https://github.com/crypto-crew-tech/cryptopia-api-python.git
```
Collecting git+https://github.com/crypto-crew-tech/cryptopia-api-python.git
  Cloning https://github.com/crypto-crew-tech/cryptopia-api-python.git to c:\users\weijie~1\appdata\local\temp\pip-be6whl54-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\wei jie\appdata\local\programs\python\python36-32\lib\tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\WEIJIE~1\\AppData\\Local\\Temp\\pip-be6whl54-build\\setup.py'

```

Anyone can help me?

**Comment by zahamat** [comment]
how do you install the module ?. ive got the same error downloadable but unable to unpack.

**Comment by saniales** [comment]
Closing and opening #42
