### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by gogothesaint** [thebotguys/cryptopia-api-python#25]
im getting the following error when running pump_dump

```
Traceback (most recent call last):
  File "pump-dump.py", line 46, in <module>
    BALANCE_BTC, ERROR = API.get_balance('BTC')
  File "/Users/george/Downloads/cryptopia-api-python-master/examples/pump-dump/cryptopia_api.py", line 103, in get_balance
    post_parameters={'Currency': currency})
  File "/Users/george/Downloads/cryptopia-api-python-master/examples/pump-dump/cryptopia_api.py", line 39, in api_query
    req = req.json()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jeivarmarr** [comment]
The same thing happens to me, some solution?

**Comment by jeivarmarr** [comment]
delete the line json.dumps (post_data) and it worked for me

`def secure_headers(self, url, post_data):
        """ Creates secure header for cryptopia private api. """
        nonce = str(int(time.time()))
        md5 = hashlib.md5()
        md5.update(post_data.encode('utf-8'))
        rcb64 = base64.b64encode(md5.digest()).decode('utf-8')
        signature = self.key + "POST" + quote_plus(url).lower() + nonce + rcb64
        hmacsignature = base64.b64encode(hmac.new(base64.b64decode(self.secret),
                                                  signature.encode('utf-8'),
                                                  hashlib.sha256).digest())
        header_value = "amx " + self.key + ":" + hmacsignature.decode('utf-8') + ":" + nonce
        return {'Authorization': header_value, 'Content-Type': 'application/json; charset=utf-8'}`
